language: ruby
sudo: false
before_install:
  - gem update --system 3.0.6
  - gem install bundler:2.0.2
rvm:
  - 2.5.5
  - 2.6.2
  - 2.7.1
  - jruby-9.2.6.0
branches:
  only:
    - master
cache: bundler
