language: ruby
sudo: false
before_install:
  - gem update --system 3.1.3
  - gem install bundler:2.1.4
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - jruby-9.2.11.1
branches:
  only:
    - master
cache: bundler
